spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: demo
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/sql/mysql/users.sql
  jpa:
    hibernate:
      ddl-auto: create-drop  #validate para produccion

---
spring:
  profiles: test mysql
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

