spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
---
spring:
  profiles: local
  datasource:
    data: classpath:/sql/h2/users.sql

